modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="owtj" #mandatory
version="${file.jarVersion}" #mandatory
displayName="One With The Jungle" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/CGessinger/OneWithTheJungle" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java and M." #optional
authors="CGessinger" #optional
description='''
One With The Jungle is an early game Mod (but might as well be used until the late game ;) ) adding different Mob-armors which give potion effects.
'''

[[dependencies.owtj]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
